run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - web/templates

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sirrobot01/protodex
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - dogsled
    - copyloopvar
    - gofmt
    - goprintffuncname
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl